language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
    - key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
script:
  - ./build.sh